"""
Añade ~80 recetas españolas y europeas a la base de datos de Ratatui.
Ejecutar con el servidor arrancado: python seed_europe.py
"""
import httpx, asyncio, json

API = "http://localhost:8000"

RECIPES = [
    # ─── ESPAÑA: TAPAS Y APERITIVOS ───────────────────────────────────────
    {
        "titulo": "Croquetas de Jamón Ibérico",
        "descripcion": "Cremosas croquetas con bechamel de jamón ibérico, crujientes por fuera y fundentes por dentro.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 60},
        "ingredientes": [
            {"nombre": "Jamón ibérico picado", "cantidad": "150", "unidad": "g"},
            {"nombre": "Mantequilla", "cantidad": "80", "unidad": "g"},
            {"nombre": "Harina", "cantidad": "100", "unidad": "g"},
            {"nombre": "Leche entera", "cantidad": "700", "unidad": "ml"},
            {"nombre": "Huevo", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Pan rallado", "cantidad": "200", "unidad": "g"},
            {"nombre": "Aceite de oliva", "cantidad": "500", "unidad": "ml"},
            {"nombre": "Nuez moscada", "cantidad": "1", "unidad": "pizca"},
        ],
        "pasos": [
            "Derretir la mantequilla y sofreír el jamón 2 minutos.",
            "Añadir la harina y tostar 3 minutos sin parar de remover.",
            "Incorporar la leche caliente poco a poco removiendo constantemente hasta obtener una bechamel espesa.",
            "Sazonar con sal y nuez moscada. Extender en una bandeja y enfriar en nevera al menos 2 horas.",
            "Formar las croquetas con dos cucharas, pasar por huevo batido y pan rallado.",
            "Freír en aceite abundante a 180 °C hasta que estén doradas.",
        ],
        "etiquetas": ["Tapa", "Frito", "España", "Jamón"],
    },
    {
        "titulo": "Gambas al Ajillo",
        "descripcion": "Gambas salteadas con ajo, guindilla y aceite de oliva, el aperitivo español por excelencia.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 2,
        "tiempos": {"total_minutos": 10},
        "ingredientes": [
            {"nombre": "Gambas peladas", "cantidad": "300", "unidad": "g"},
            {"nombre": "Ajo", "cantidad": "6", "unidad": "dientes"},
            {"nombre": "Guindilla seca", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "80", "unidad": "ml"},
            {"nombre": "Perejil fresco", "cantidad": "1", "unidad": "manojo"},
            {"nombre": "Sal", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Calentar el aceite en una cazuela de barro a fuego medio.",
            "Sofreír el ajo laminado y la guindilla hasta que el ajo empiece a dorarse.",
            "Añadir las gambas, subir el fuego y saltear 2 minutos hasta que estén rosas.",
            "Sazonar con sal, espolvorear perejil picado y servir inmediatamente en la cazuela.",
        ],
        "etiquetas": ["Tapa", "Mariscos", "España", "Rápido"],
    },
    {
        "titulo": "Patatas Bravas con Salsa Picante",
        "descripcion": "Patatas fritas crujientes con la icónica salsa brava, protagonistas de cualquier bar español.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 35},
        "ingredientes": [
            {"nombre": "Patatas", "cantidad": "800", "unidad": "g"},
            {"nombre": "Tomate frito", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Pimentón picante", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Pimentón dulce", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Vinagre", "cantidad": "1", "unidad": "cucharada"},
            {"nombre": "Ajo", "cantidad": "2", "unidad": "dientes"},
            {"nombre": "Aceite de oliva", "cantidad": "500", "unidad": "ml"},
        ],
        "pasos": [
            "Pelar y trocear las patatas en dados de 3 cm. Secar bien.",
            "Freír a 160 °C 8 minutos (primer frito). Reservar.",
            "Subir el aceite a 190 °C y freír de nuevo 3 minutos hasta que queden doradas y crujientes.",
            "Para la salsa: sofreír el ajo picado, añadir tomate frito, pimentones y vinagre. Triturar.",
            "Servir las patatas con la salsa por encima.",
        ],
        "etiquetas": ["Tapa", "España", "Patatas", "Vegano"],
    },
    {
        "titulo": "Pan con Tomate (Pa amb Tomàquet)",
        "descripcion": "El desayuno y aperitivo catalán más sencillo y delicioso: pan de cristal con tomate maduro y aceite.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 2,
        "tiempos": {"total_minutos": 5},
        "ingredientes": [
            {"nombre": "Pan de cristal o baguette", "cantidad": "4", "unidad": "rebanadas"},
            {"nombre": "Tomate maduro", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "4", "unidad": "cucharadas"},
            {"nombre": "Ajo", "cantidad": "1", "unidad": "diente"},
            {"nombre": "Sal en escamas", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Tostar el pan.",
            "Frotar el ajo por la superficie del pan.",
            "Partir el tomate por la mitad y frotar generosamente sobre el pan.",
            "Regar con aceite de oliva y sal en escamas.",
        ],
        "etiquetas": ["Cataluña", "Desayuno", "España", "Vegano", "Rápido"],
    },
    {
        "titulo": "Boquerones en Vinagre",
        "descripcion": "Boquerones marinados en vinagre y aliñados con ajo y perejil, un clásico de la tapa española.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 30},
        "ingredientes": [
            {"nombre": "Boquerones frescos limpios", "cantidad": "400", "unidad": "g"},
            {"nombre": "Vinagre de vino blanco", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "100", "unidad": "ml"},
            {"nombre": "Ajo", "cantidad": "3", "unidad": "dientes"},
            {"nombre": "Perejil fresco", "cantidad": "1", "unidad": "manojo"},
            {"nombre": "Sal", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Limpiar los boquerones, separar los filetes y lavarlos bien.",
            "Cubrirlos con vinagre y sal. Dejar marinar en nevera mínimo 4 horas (hasta que estén blancos).",
            "Escurrir el vinagre, aliñar con aceite de oliva, ajo picado y perejil.",
            "Servir frío.",
        ],
        "etiquetas": ["Tapa", "España", "Pescado", "Sin cocción"],
    },
    # ─── ESPAÑA: COCIDOS Y GUISOS ─────────────────────────────────────────
    {
        "titulo": "Cocido Madrileño",
        "descripcion": "El guiso más representativo de Madrid: garbanzos con carnes del cocido, chorizo, morcilla y verduras.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 6,
        "tiempos": {"total_minutos": 180},
        "ingredientes": [
            {"nombre": "Garbanzos secos", "cantidad": "500", "unidad": "g"},
            {"nombre": "Morcillo de ternera", "cantidad": "400", "unidad": "g"},
            {"nombre": "Pollo troceado", "cantidad": "300", "unidad": "g"},
            {"nombre": "Tocino ibérico", "cantidad": "150", "unidad": "g"},
            {"nombre": "Chorizo", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Morcilla", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Hueso de caña", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Zanahoria", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Patatas", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Repollo", "cantidad": "1/2", "unidad": "pieza"},
        ],
        "pasos": [
            "Poner los garbanzos a remojo la noche anterior.",
            "Hervir las carnes con el hueso y el tocino desde agua fría. Desespumar.",
            "Añadir los garbanzos y cocer a fuego lento 1.5 horas.",
            "Añadir las verduras y cocer 30 minutos más. Añadir los embutidos los últimos 20 minutos.",
            "Servir en tres vuelcos: primero el caldo con fideos, luego los garbanzos con verdura, finalmente las carnes.",
        ],
        "etiquetas": ["Madrid", "Guiso", "España", "Legumbres"],
    },
    {
        "titulo": "Fabada Asturiana",
        "descripcion": "El potaje asturiano por excelencia: fabes grandes y mantecosas con chorizo, morcilla y lacón.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 6,
        "tiempos": {"total_minutos": 180},
        "ingredientes": [
            {"nombre": "Fabes asturianas", "cantidad": "500", "unidad": "g"},
            {"nombre": "Chorizo asturiano", "cantidad": "200", "unidad": "g"},
            {"nombre": "Morcilla asturiana", "cantidad": "200", "unidad": "g"},
            {"nombre": "Lacón", "cantidad": "300", "unidad": "g"},
            {"nombre": "Tocino", "cantidad": "100", "unidad": "g"},
            {"nombre": "Azafrán", "cantidad": "1", "unidad": "pizca"},
            {"nombre": "Sal", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Poner las fabes a remojo en agua fría 12 horas.",
            "Colocar todos los ingredientes en una olla grande cubiertos de agua fría.",
            "Llevar a ebullición, desespumar y reducir al mínimo. Cocer 2.5 horas a fuego muy lento.",
            "Asustar las fabes con un chorro de agua fría 3 veces durante la cocción para que queden enteras.",
            "Rectificar de sal y servir caliente.",
        ],
        "etiquetas": ["Asturias", "Guiso", "España", "Legumbres"],
    },
    {
        "titulo": "Guiso de Lentejas a la Española",
        "descripcion": "Lentejas pardinas con chorizo, morcilla, zanahoria y patata en un caldo sabroso y reconfortante.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 50},
        "ingredientes": [
            {"nombre": "Lentejas pardinas", "cantidad": "400", "unidad": "g"},
            {"nombre": "Chorizo", "cantidad": "150", "unidad": "g"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Zanahoria", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Patata", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Ajo", "cantidad": "3", "unidad": "dientes"},
            {"nombre": "Tomate frito", "cantidad": "2", "unidad": "cucharadas"},
            {"nombre": "Pimentón dulce", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Aceite de oliva", "cantidad": "3", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Sofreír la cebolla, el ajo y el chorizo en aceite.",
            "Añadir el pimentón, el tomate y las verduras troceadas.",
            "Incorporar las lentejas enjuagadas y cubrir con agua fría. No remojar.",
            "Cocer a fuego medio 30-35 minutos hasta que las lentejas estén tiernas.",
            "Rectificar de sal y servir caliente.",
        ],
        "etiquetas": ["España", "Legumbres", "Invierno", "Económico"],
    },
    {
        "titulo": "Pisto Manchego",
        "descripcion": "El pisto manchego es un sofrito de verduras de verano en aceite de oliva, versátil y delicioso.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 45},
        "ingredientes": [
            {"nombre": "Calabacín", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Pimiento rojo", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Pimiento verde", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Tomate maduro", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Ajo", "cantidad": "2", "unidad": "dientes"},
            {"nombre": "Aceite de oliva", "cantidad": "5", "unidad": "cucharadas"},
            {"nombre": "Sal y azúcar", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Picar todas las verduras en dados pequeños.",
            "Sofreír la cebolla y el ajo a fuego lento 10 minutos.",
            "Añadir los pimientos y cocer 10 minutos más.",
            "Incorporar el calabacín y el tomate. Cocer 20-25 minutos a fuego lento hasta que todo esté tierno.",
            "Rectificar de sal. Servir solo, con huevo frito o sobre tostada.",
        ],
        "etiquetas": ["Castilla-La Mancha", "Vegano", "España", "Verduras"],
    },
    {
        "titulo": "Sopa de Ajo Castellana",
        "descripcion": "Sopas de ajo con pan duro, pimentón y huevo, el plato humilde y reconfortante de Castilla.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 25},
        "ingredientes": [
            {"nombre": "Pan del día anterior", "cantidad": "200", "unidad": "g"},
            {"nombre": "Ajo", "cantidad": "8", "unidad": "dientes"},
            {"nombre": "Pimentón dulce", "cantidad": "2", "unidad": "cucharaditas"},
            {"nombre": "Huevos", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Caldo de pollo o agua", "cantidad": "1.5", "unidad": "litros"},
            {"nombre": "Aceite de oliva", "cantidad": "4", "unidad": "cucharadas"},
            {"nombre": "Sal", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Sofreír el ajo laminado en aceite sin que se queme.",
            "Añadir el pan troceado y el pimentón. Sofreír 2 minutos.",
            "Verter el caldo caliente y cocer 10 minutos.",
            "Cascar un huevo por encima de cada cazuelita de barro y hornear a 180 °C 5 minutos.",
            "Servir inmediatamente en las cazuelitas.",
        ],
        "etiquetas": ["Castilla", "Sopa", "España", "Invierno"],
    },
    # ─── ESPAÑA: PESCADOS Y MARISCOS ─────────────────────────────────────
    {
        "titulo": "Bacalao al Pil-Pil",
        "descripcion": "Técnica vasca que emulsiona el colágeno del bacalao con aceite para crear una salsa sedosa y gelantinosa.",
        "tipo_cocina": "Española",
        "dificultad": "Difícil",
        "porciones": 4,
        "tiempos": {"total_minutos": 40},
        "ingredientes": [
            {"nombre": "Lomos de bacalao desalado", "cantidad": "800", "unidad": "g"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "300", "unidad": "ml"},
            {"nombre": "Ajo", "cantidad": "6", "unidad": "dientes"},
            {"nombre": "Guindilla", "cantidad": "1", "unidad": "pieza"},
        ],
        "pasos": [
            "Confitar el ajo y la guindilla en aceite a 60 °C 15 minutos. Retirar.",
            "Añadir el bacalao con la piel hacia arriba en el mismo aceite frío.",
            "Cocer a fuego muy bajo durante 15 minutos, moviendo suavemente la cazuela.",
            "Retirar el bacalao y emulsionar el aceite con la gelatina del pescado moviendo la cazuela en círculos.",
            "Montar el pil-pil hasta que la salsa espese y adquiera color nacarado.",
        ],
        "etiquetas": ["País Vasco", "Pescado", "España", "Sin gluten"],
    },
    {
        "titulo": "Merluza en Salsa Verde",
        "descripcion": "Merluza en salsa de perejil y ajo, un clásico de la cocina vasca ligero y elegante.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 25},
        "ingredientes": [
            {"nombre": "Rodajas de merluza", "cantidad": "800", "unidad": "g"},
            {"nombre": "Ajo", "cantidad": "4", "unidad": "dientes"},
            {"nombre": "Perejil fresco", "cantidad": "1", "unidad": "manojo"},
            {"nombre": "Harina", "cantidad": "2", "unidad": "cucharadas"},
            {"nombre": "Caldo de pescado", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Aceite de oliva", "cantidad": "4", "unidad": "cucharadas"},
            {"nombre": "Almejas", "cantidad": "200", "unidad": "g"},
        ],
        "pasos": [
            "Enharinar ligeramente las rodajas de merluza y dorarlas en aceite.",
            "Sofreír el ajo picado en el mismo aceite, añadir harina y tostar.",
            "Verter el caldo de pescado y mover la cazuela en círculos.",
            "Añadir el perejil picado y las almejas. Cocer 5 minutos.",
            "Incorporar la merluza con cuidado y cocer 5 minutos más.",
        ],
        "etiquetas": ["País Vasco", "Pescado", "España", "Sin gluten"],
    },
    {
        "titulo": "Pulpo a Feira",
        "descripcion": "Pulpo cocido al estilo gallego, cortado en rodajas y aliñado con pimentón de La Vera y aceite de oliva.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 60},
        "ingredientes": [
            {"nombre": "Pulpo", "cantidad": "1.5", "unidad": "kg"},
            {"nombre": "Patatas gallegas", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Pimentón de La Vera dulce", "cantidad": "2", "unidad": "cucharaditas"},
            {"nombre": "Pimentón picante", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "5", "unidad": "cucharadas"},
            {"nombre": "Sal gruesa", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Congelar el pulpo previamente para ablandarlo. Descongelar.",
            "Hervir agua con sal. Cuando burbujee, sumergir el pulpo 3 veces antes de cocerlo (asustar).",
            "Cocer el pulpo 40-45 minutos hasta que esté tierno. Pinchar para comprobar.",
            "Cocer las patatas en el mismo agua.",
            "Servir el pulpo y las patatas en tabla de madera. Aliñar con pimentón y aceite.",
        ],
        "etiquetas": ["Galicia", "Mariscos", "España", "Sin gluten"],
    },
    # ─── ESPAÑA: CARNES ───────────────────────────────────────────────────
    {
        "titulo": "Pollo al Ajillo",
        "descripcion": "Trozos de pollo salteados con ajo y vino blanco, una tapa y plato principal clásico español.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 30},
        "ingredientes": [
            {"nombre": "Pollo troceado", "cantidad": "1", "unidad": "kg"},
            {"nombre": "Ajo", "cantidad": "10", "unidad": "dientes"},
            {"nombre": "Vino blanco", "cantidad": "150", "unidad": "ml"},
            {"nombre": "Aceite de oliva", "cantidad": "4", "unidad": "cucharadas"},
            {"nombre": "Hojas de laurel", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Perejil", "cantidad": "1", "unidad": "manojo"},
            {"nombre": "Sal y pimienta", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Salpimentar los trozos de pollo y dorarlos bien en aceite caliente.",
            "Añadir los ajos enteros y el laurel. Sofreír 2 minutos.",
            "Verter el vino blanco y dejar evaporar el alcohol 2 minutos.",
            "Tapar y cocer a fuego medio 15-20 minutos hasta que el pollo esté tierno.",
            "Espolvorear perejil picado y servir.",
        ],
        "etiquetas": ["España", "Pollo", "Rápido"],
    },
    {
        "titulo": "Albóndigas en Salsa de Tomate",
        "descripcion": "Tiernas albóndigas de carne picada en una salsa de tomate casera con verduras.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 50},
        "ingredientes": [
            {"nombre": "Carne picada mixta (ternera+cerdo)", "cantidad": "600", "unidad": "g"},
            {"nombre": "Huevo", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Pan rallado", "cantidad": "50", "unidad": "g"},
            {"nombre": "Ajo picado", "cantidad": "2", "unidad": "dientes"},
            {"nombre": "Tomate triturado", "cantidad": "400", "unidad": "g"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Pimiento verde", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Vino blanco", "cantidad": "100", "unidad": "ml"},
        ],
        "pasos": [
            "Mezclar la carne con huevo, pan rallado, ajo, sal y perejil. Formar albóndigas.",
            "Enharinar y freír las albóndigas hasta dorarlas. Reservar.",
            "En el mismo aceite, sofreír cebolla y pimiento. Añadir tomate y vino.",
            "Cocer la salsa 10 minutos. Incorporar las albóndigas y cocer 15 minutos más.",
        ],
        "etiquetas": ["España", "Carne", "Tradicional"],
    },
    # ─── ESPAÑA: POSTRES ─────────────────────────────────────────────────
    {
        "titulo": "Crema Catalana",
        "descripcion": "Crema pastelera con corteza de azúcar quemado, el postre más emblemático de Cataluña.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 30},
        "ingredientes": [
            {"nombre": "Leche entera", "cantidad": "500", "unidad": "ml"},
            {"nombre": "Yemas de huevo", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Azúcar", "cantidad": "100", "unidad": "g"},
            {"nombre": "Maicena", "cantidad": "20", "unidad": "g"},
            {"nombre": "Corteza de limón", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Canela en rama", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Azúcar moreno para quemar", "cantidad": "4", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Infusionar la leche con la corteza de limón y la canela.",
            "Mezclar las yemas con el azúcar y la maicena.",
            "Verter la leche caliente sobre las yemas removiendo. Devolver al fuego.",
            "Cocer a fuego bajo removiendo hasta que espese.",
            "Repartir en cazuelitas y enfriar. Espolvorear azúcar moreno y quemar con soplete.",
        ],
        "etiquetas": ["Cataluña", "Postre", "España"],
    },
    {
        "titulo": "Arroz con Leche",
        "descripcion": "Cremoso postre de arroz cocido con leche, canela y limón, el consuelo de la cocina española.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 50},
        "ingredientes": [
            {"nombre": "Arroz de grano redondo", "cantidad": "150", "unidad": "g"},
            {"nombre": "Leche entera", "cantidad": "1", "unidad": "litro"},
            {"nombre": "Azúcar", "cantidad": "120", "unidad": "g"},
            {"nombre": "Corteza de limón", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Canela en rama", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Canela molida para decorar", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Hervir el arroz 5 minutos en agua. Escurrir.",
            "Calentar la leche con la corteza de limón y la canela en rama.",
            "Añadir el arroz a la leche y cocer a fuego lento 30-35 minutos removiendo frecuentemente.",
            "Añadir el azúcar los últimos 5 minutos. La crema debe quedar espesa.",
            "Enfriar y servir con canela molida por encima.",
        ],
        "etiquetas": ["España", "Postre", "Arroz"],
    },
    {
        "titulo": "Tarta de Santiago",
        "descripcion": "El pastel de almendra gallego con la Cruz de Santiago, postre sin harina y sin gluten.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 8,
        "tiempos": {"total_minutos": 45},
        "ingredientes": [
            {"nombre": "Almendra molida", "cantidad": "250", "unidad": "g"},
            {"nombre": "Azúcar", "cantidad": "200", "unidad": "g"},
            {"nombre": "Huevos", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Ralladura de limón", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Ralladura de naranja", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Azúcar glass para decorar", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Mezclar la almendra molida con el azúcar.",
            "Añadir los huevos batidos y las ralladuras. Mezclar bien.",
            "Verter en un molde desmontable engrasado.",
            "Hornear a 180 °C 30-35 minutos hasta que esté dorada.",
            "Enfriar, espolvorear azúcar glass con la Cruz de Santiago como plantilla.",
        ],
        "etiquetas": ["Galicia", "Postre", "España", "Sin gluten"],
    },
    {
        "titulo": "Churros con Chocolate a la Taza",
        "descripcion": "Churros caseros crujientes para mojar en chocolate espeso, el desayuno festivo español.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 30},
        "ingredientes": [
            {"nombre": "Harina", "cantidad": "200", "unidad": "g"},
            {"nombre": "Agua hirviendo", "cantidad": "250", "unidad": "ml"},
            {"nombre": "Sal", "cantidad": "1", "unidad": "pizca"},
            {"nombre": "Aceite de oliva para freír", "cantidad": "500", "unidad": "ml"},
            {"nombre": "Chocolate negro 70%", "cantidad": "200", "unidad": "g"},
            {"nombre": "Leche entera", "cantidad": "400", "unidad": "ml"},
            {"nombre": "Azúcar", "cantidad": "3", "unidad": "cucharadas"},
            {"nombre": "Maicena", "cantidad": "1", "unidad": "cucharada"},
        ],
        "pasos": [
            "Mezclar la harina con el agua hirviendo y la sal hasta obtener una masa homogénea.",
            "Llenar una churrera o manga pastelera y freír los churros en aceite a 180 °C.",
            "Escurrir sobre papel y espolvorear con azúcar.",
            "Para el chocolate: calentar la leche, disolver la maicena y el chocolate troceado. Remover hasta espesar.",
        ],
        "etiquetas": ["España", "Desayuno", "Postre"],
    },
    # ─── FRANCIA ─────────────────────────────────────────────────────────
    {
        "titulo": "Coq au Vin",
        "descripcion": "Pollo braseado con vino tinto, champiñones, tocino y hierbas aromáticas, un clásico francés de la cocina bistró.",
        "tipo_cocina": "Francesa",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 90},
        "ingredientes": [
            {"nombre": "Pollo troceado", "cantidad": "1.5", "unidad": "kg"},
            {"nombre": "Vino tinto Borgoña", "cantidad": "750", "unidad": "ml"},
            {"nombre": "Tocino ahumado", "cantidad": "150", "unidad": "g"},
            {"nombre": "Champiñones", "cantidad": "250", "unidad": "g"},
            {"nombre": "Cebollitas francesas", "cantidad": "200", "unidad": "g"},
            {"nombre": "Ajo", "cantidad": "3", "unidad": "dientes"},
            {"nombre": "Tomillo, laurel, romero", "cantidad": "1", "unidad": "bouquet"},
            {"nombre": "Brandy", "cantidad": "50", "unidad": "ml"},
        ],
        "pasos": [
            "Marinar el pollo en el vino con hierbas 12 horas. Escurrir y secar.",
            "Dorar el pollo en mantequilla. Flambear con brandy.",
            "Sofreír el tocino, cebollitas y champiñones.",
            "Añadir el vino de la marinada y el pollo. Cocer 45 minutos a fuego lento.",
            "Reducir la salsa y servir con pan rústico.",
        ],
        "etiquetas": ["Francia", "Pollo", "Vino"],
    },
    {
        "titulo": "Crêpes Suzette",
        "descripcion": "Finos crepes flambados con mantequilla de naranja y Grand Marnier, el postre francés más espectacular.",
        "tipo_cocina": "Francesa",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 30},
        "ingredientes": [
            {"nombre": "Harina", "cantidad": "125", "unidad": "g"},
            {"nombre": "Huevos", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Leche", "cantidad": "300", "unidad": "ml"},
            {"nombre": "Mantequilla", "cantidad": "50", "unidad": "g"},
            {"nombre": "Zumo de naranja", "cantidad": "150", "unidad": "ml"},
            {"nombre": "Ralladura de naranja", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Grand Marnier o Cointreau", "cantidad": "60", "unidad": "ml"},
            {"nombre": "Azúcar", "cantidad": "50", "unidad": "g"},
        ],
        "pasos": [
            "Hacer la masa de crepes mezclando harina, huevos, leche y mantequilla derretida. Reposar 30 minutos.",
            "Cocinar los crepes en sartén antiadherente.",
            "En otra sartén, caramelizar el azúcar, añadir zumo y ralladura de naranja y mantequilla.",
            "Pasar los crepes doblados por la salsa de naranja.",
            "Verter el licor y flambar. Servir inmediatamente.",
        ],
        "etiquetas": ["Francia", "Postre", "Flambeado"],
    },
    {
        "titulo": "Tarte Tatin",
        "descripcion": "La famosa tarta francesa de manzana caramelizada al revés, crujiente y fundente a la vez.",
        "tipo_cocina": "Francesa",
        "dificultad": "Media",
        "porciones": 6,
        "tiempos": {"total_minutos": 55},
        "ingredientes": [
            {"nombre": "Manzanas Golden o Reineta", "cantidad": "6", "unidad": "piezas"},
            {"nombre": "Azúcar", "cantidad": "150", "unidad": "g"},
            {"nombre": "Mantequilla", "cantidad": "80", "unidad": "g"},
            {"nombre": "Masa quebrada o hojaldre", "cantidad": "200", "unidad": "g"},
            {"nombre": "Canela", "cantidad": "1", "unidad": "cucharadita"},
        ],
        "pasos": [
            "Pelar y cuartear las manzanas.",
            "Caramelizar el azúcar con la mantequilla en una sartén apta para horno.",
            "Colocar las manzanas encima, añadir canela y cocer 10 minutos.",
            "Cubrir con la masa estirada y meter los bordes por dentro.",
            "Hornear a 200 °C 25 minutos. Desmoldar inmediatamente dando la vuelta.",
        ],
        "etiquetas": ["Francia", "Postre", "Manzana"],
    },
    {
        "titulo": "Vichyssoise",
        "descripcion": "Crema fría de puerros y patata, elegante y refrescante, perfecta como entrante en verano.",
        "tipo_cocina": "Francesa",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 40},
        "ingredientes": [
            {"nombre": "Puerros (parte blanca)", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Patatas", "cantidad": "400", "unidad": "g"},
            {"nombre": "Caldo de pollo", "cantidad": "800", "unidad": "ml"},
            {"nombre": "Nata líquida", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Mantequilla", "cantidad": "30", "unidad": "g"},
            {"nombre": "Cebollino para decorar", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Pochar los puerros en mantequilla a fuego lento 10 minutos.",
            "Añadir las patatas peladas y troceadas y el caldo. Cocer 20 minutos.",
            "Triturar hasta obtener una crema fina. Colar.",
            "Añadir la nata, salpimentar y enfriar en nevera.",
            "Servir bien fría con cebollino picado.",
        ],
        "etiquetas": ["Francia", "Sopa", "Verano", "Frío"],
    },
    {
        "titulo": "Croissant de Mantequilla",
        "descripcion": "El bollito hojaldrado parisino por excelencia, hecho con mantequilla de calidad y laminado a mano.",
        "tipo_cocina": "Francesa",
        "dificultad": "Difícil",
        "porciones": 8,
        "tiempos": {"total_minutos": 360},
        "ingredientes": [
            {"nombre": "Harina de fuerza", "cantidad": "500", "unidad": "g"},
            {"nombre": "Mantequilla en bloque (para laminar)", "cantidad": "250", "unidad": "g"},
            {"nombre": "Leche", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Levadura fresca", "cantidad": "20", "unidad": "g"},
            {"nombre": "Azúcar", "cantidad": "50", "unidad": "g"},
            {"nombre": "Sal", "cantidad": "10", "unidad": "g"},
            {"nombre": "Yema de huevo para pintar", "cantidad": "1", "unidad": "pieza"},
        ],
        "pasos": [
            "Hacer la masa con harina, leche, levadura, azúcar y sal. Fermentar 1 hora en nevera.",
            "Estirar la masa y encerrar la mantequilla fría. Hacer 3 pliegues sencillos enfriando 30 min entre cada uno.",
            "Estirar la masa final a 3 mm y cortar triángulos.",
            "Enrollar cada triángulo y dar la forma de croissant. Fermentar 2 horas a temperatura ambiente.",
            "Pintar con yema y hornear a 190 °C 18-20 minutos hasta que estén dorados.",
        ],
        "etiquetas": ["Francia", "Bollería", "Desayuno"],
    },
    # ─── ITALIA ───────────────────────────────────────────────────────────
    {
        "titulo": "Pizza Margherita Napolitana",
        "descripcion": "La pizza más sencilla y perfecta: masa de fermentación lenta, tomate San Marzano y mozzarella de búfala.",
        "tipo_cocina": "Italiana",
        "dificultad": "Media",
        "porciones": 2,
        "tiempos": {"total_minutos": 60},
        "ingredientes": [
            {"nombre": "Harina tipo 00", "cantidad": "300", "unidad": "g"},
            {"nombre": "Agua", "cantidad": "195", "unidad": "ml"},
            {"nombre": "Levadura fresca", "cantidad": "3", "unidad": "g"},
            {"nombre": "Sal", "cantidad": "7", "unidad": "g"},
            {"nombre": "Tomate San Marzano triturado", "cantidad": "150", "unidad": "g"},
            {"nombre": "Mozzarella di bufala", "cantidad": "200", "unidad": "g"},
            {"nombre": "Hojas de albahaca", "cantidad": "10", "unidad": "hojas"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "2", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Mezclar harina, agua, levadura y sal. Amasar 10 minutos. Fermentar 24 h en nevera.",
            "Precalentar el horno al máximo con la piedra de pizza o bandeja dentro.",
            "Estirar la masa a mano (no rodillo) hasta un grosor de 3-4 mm.",
            "Cubrir con tomate sazonado con sal y aceite. Hornear 8 minutos.",
            "Añadir la mozzarella y hornear 2 minutos más. Terminar con albahaca fresca.",
        ],
        "etiquetas": ["Italia", "Pizza", "Vegetariana"],
    },
    {
        "titulo": "Gnocchi al Pesto Genovese",
        "descripcion": "Ñoquis de patata caseros con el auténtico pesto genovés de albahaca, piñones y Parmigiano.",
        "tipo_cocina": "Italiana",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 50},
        "ingredientes": [
            {"nombre": "Patatas harinosas", "cantidad": "700", "unidad": "g"},
            {"nombre": "Harina", "cantidad": "200", "unidad": "g"},
            {"nombre": "Yema de huevo", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Albahaca fresca", "cantidad": "60", "unidad": "g"},
            {"nombre": "Piñones", "cantidad": "30", "unidad": "g"},
            {"nombre": "Parmigiano Reggiano", "cantidad": "60", "unidad": "g"},
            {"nombre": "Ajo", "cantidad": "1", "unidad": "diente"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "100", "unidad": "ml"},
        ],
        "pasos": [
            "Cocer las patatas enteras con piel. Pelar y pasar por pasapurés.",
            "Mezclar con harina, yema y sal hasta obtener una masa que no se pegue.",
            "Formar rollos y cortar los ñoquis. Pasar cada uno por un tenedor.",
            "Hacer el pesto en mortero: albahaca + piñones + ajo + Parmigiano + aceite.",
            "Cocer los ñoquis en agua salada hasta que suban a la superficie. Mezclar con el pesto.",
        ],
        "etiquetas": ["Italia", "Pasta", "Vegetariana"],
    },
    {
        "titulo": "Cacio e Pepe",
        "descripcion": "La pasta romana más minimalista: solo tonnarelli, queso Pecorino Romano y pimienta negra.",
        "tipo_cocina": "Italiana",
        "dificultad": "Media",
        "porciones": 2,
        "tiempos": {"total_minutos": 20},
        "ingredientes": [
            {"nombre": "Tonnarelli o espaguetis", "cantidad": "200", "unidad": "g"},
            {"nombre": "Pecorino Romano rallado", "cantidad": "100", "unidad": "g"},
            {"nombre": "Parmigiano Reggiano rallado", "cantidad": "50", "unidad": "g"},
            {"nombre": "Pimienta negra en grano", "cantidad": "1.5", "unidad": "cucharaditas"},
            {"nombre": "Sal", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Tostar la pimienta en sartén y moler gruesa.",
            "Cocer la pasta en poca agua muy salada.",
            "Mezclar los quesos rallados con agua de cocción para hacer una crema.",
            "Escurrir la pasta (reservar agua), mezclar con la pimienta y la crema de queso.",
            "Añadir agua de cocción poco a poco hasta que la salsa sea cremosa y brillante.",
        ],
        "etiquetas": ["Italia", "Pasta", "Roma", "Vegetariana"],
    },
    {
        "titulo": "Focaccia Genovese",
        "descripcion": "El pan plano italiano con aceite de oliva, sal marina y romero, crujiente por fuera y esponjoso por dentro.",
        "tipo_cocina": "Italiana",
        "dificultad": "Fácil",
        "porciones": 6,
        "tiempos": {"total_minutos": 90},
        "ingredientes": [
            {"nombre": "Harina de fuerza", "cantidad": "500", "unidad": "g"},
            {"nombre": "Agua", "cantidad": "350", "unidad": "ml"},
            {"nombre": "Levadura fresca", "cantidad": "15", "unidad": "g"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "80", "unidad": "ml"},
            {"nombre": "Sal marina en escamas", "cantidad": "10", "unidad": "g"},
            {"nombre": "Romero fresco", "cantidad": "2", "unidad": "ramas"},
        ],
        "pasos": [
            "Mezclar harina, levadura, agua y 40 ml de aceite. Amasar 8 minutos.",
            "Fermentar 1 hora en recipiente aceitado.",
            "Extender en bandeja aceitada haciendo hoyuelos con los dedos.",
            "Regar con el aceite restante mezclado con agua y sal. Fermentar 30 min más.",
            "Hornear a 220 °C 20-25 minutos hasta dorar. Añadir romero y sal en escamas.",
        ],
        "etiquetas": ["Italia", "Pan", "Vegetariana", "Vegano"],
    },
    {
        "titulo": "Panna Cotta con Frutos Rojos",
        "descripcion": "Postre italiano de nata cuajada con gelatina, suave como la seda, con coulis de frutos rojos.",
        "tipo_cocina": "Italiana",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 20},
        "ingredientes": [
            {"nombre": "Nata para montar", "cantidad": "500", "unidad": "ml"},
            {"nombre": "Azúcar", "cantidad": "60", "unidad": "g"},
            {"nombre": "Gelatina en láminas", "cantidad": "4", "unidad": "hojas"},
            {"nombre": "Vaina de vainilla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Frutos rojos mixtos", "cantidad": "200", "unidad": "g"},
            {"nombre": "Azúcar para el coulis", "cantidad": "30", "unidad": "g"},
        ],
        "pasos": [
            "Hidratar las hojas de gelatina en agua fría 5 minutos.",
            "Calentar la nata con el azúcar y la vainilla raspada hasta casi hervir.",
            "Escurrir la gelatina y disolver en la nata caliente.",
            "Verter en moldes y enfriar en nevera 4 horas.",
            "Triturar los frutos rojos con azúcar para el coulis. Desmoldar y servir con el coulis.",
        ],
        "etiquetas": ["Italia", "Postre", "Sin gluten", "Sin horno"],
    },
    {
        "titulo": "Ribollita Toscana",
        "descripcion": "Contundente sopa toscana de pan, alubias y verduras de invierno, que se vuelve a hervir al día siguiente.",
        "tipo_cocina": "Italiana",
        "dificultad": "Fácil",
        "porciones": 6,
        "tiempos": {"total_minutos": 80},
        "ingredientes": [
            {"nombre": "Alubias blancas cocidas", "cantidad": "400", "unidad": "g"},
            {"nombre": "Col negra (cavolo nero)", "cantidad": "300", "unidad": "g"},
            {"nombre": "Zanahoria", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Apio", "cantidad": "2", "unidad": "ramas"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Tomates pelados", "cantidad": "400", "unidad": "g"},
            {"nombre": "Pan toscano del día anterior", "cantidad": "300", "unidad": "g"},
            {"nombre": "Aceite de oliva virgen extra", "cantidad": "80", "unidad": "ml"},
        ],
        "pasos": [
            "Sofreír cebolla, zanahoria y apio en aceite (soffritto).",
            "Añadir tomates, alubias y caldo. Cocer 30 minutos.",
            "Incorporar la col y el pan troceado. Cocer 20 minutos más.",
            "Dejar reposar. Al día siguiente, volver a hervir (ribollire) y terminar con aceite crudo.",
        ],
        "etiquetas": ["Italia", "Toscana", "Sopa", "Vegano"],
    },
    # ─── ALEMANIA Y CENTROEUROPA ──────────────────────────────────────────
    {
        "titulo": "Wiener Schnitzel",
        "descripcion": "El escalope vienés empanado con pan rallado y frito en mantequilla clarificada, símbolo de Austria.",
        "tipo_cocina": "Austriaca",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 25},
        "ingredientes": [
            {"nombre": "Filetes de ternera finos", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Harina", "cantidad": "80", "unidad": "g"},
            {"nombre": "Huevos", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Pan rallado fino", "cantidad": "150", "unidad": "g"},
            {"nombre": "Mantequilla clarificada", "cantidad": "100", "unidad": "g"},
            {"nombre": "Limón", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Sal y pimienta", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Aplanar los filetes con un mazo hasta 3 mm. Salpimentar.",
            "Pasar por harina, luego por huevo batido, luego por pan rallado. No presionar.",
            "Freír en mantequilla clarificada abundante y caliente, moviendo la sartén para que la capa quede hueca.",
            "Escurrir sobre papel. Servir con limón y ensalada de patata.",
        ],
        "etiquetas": ["Austria", "Ternera", "Empanado"],
    },
    {
        "titulo": "Bratwurst con Chucrut",
        "descripcion": "Salchicha alemana asada con chucrut al vino blanco, la combinación más icónica de Alemania.",
        "tipo_cocina": "Alemana",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 30},
        "ingredientes": [
            {"nombre": "Bratwurst (salchicha alemana)", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Chucrut", "cantidad": "500", "unidad": "g"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Vino blanco seco", "cantidad": "150", "unidad": "ml"},
            {"nombre": "Granos de pimienta", "cantidad": "6", "unidad": "piezas"},
            {"nombre": "Mostaza alemana para servir", "cantidad": "al gusto", "unidad": ""},
        ],
        "pasos": [
            "Sofreír la cebolla en manteca. Añadir el chucrut, el vino y los granos de pimienta.",
            "Cocer a fuego lento 20 minutos.",
            "Mientras, asar las bratwurst en plancha o parrilla hasta que estén bien doradas.",
            "Servir las salchichas sobre el chucrut con mostaza y pan de centeno.",
        ],
        "etiquetas": ["Alemania", "Cerdo", "Tradicional"],
    },
    {
        "titulo": "Apple Strudel (Apfelstrudel)",
        "descripcion": "El strudel de manzana austríaco con masa finísima, canela y pasas, con nata o helado de vainilla.",
        "tipo_cocina": "Austriaca",
        "dificultad": "Difícil",
        "porciones": 6,
        "tiempos": {"total_minutos": 75},
        "ingredientes": [
            {"nombre": "Harina", "cantidad": "250", "unidad": "g"},
            {"nombre": "Agua tibia", "cantidad": "130", "unidad": "ml"},
            {"nombre": "Aceite vegetal", "cantidad": "2", "unidad": "cucharadas"},
            {"nombre": "Manzanas Reineta", "cantidad": "6", "unidad": "piezas"},
            {"nombre": "Azúcar moreno", "cantidad": "80", "unidad": "g"},
            {"nombre": "Canela molida", "cantidad": "2", "unidad": "cucharaditas"},
            {"nombre": "Pasas", "cantidad": "60", "unidad": "g"},
            {"nombre": "Pan rallado tostado en mantequilla", "cantidad": "60", "unidad": "g"},
        ],
        "pasos": [
            "Hacer la masa mezclando harina, agua y aceite. Amasar hasta que esté elástica. Reposar 30 min.",
            "Estirar la masa sobre un mantel enharinado hasta que sea casi transparente.",
            "Pintar con mantequilla derretida y esparcir el pan rallado.",
            "Mezclar las manzanas peladas y laminadas con azúcar, canela y pasas.",
            "Distribuir el relleno sobre la masa y enrollar con ayuda del mantel. Pintar con mantequilla.",
            "Hornear a 190 °C 35-40 minutos hasta que esté dorado y crujiente.",
        ],
        "etiquetas": ["Austria", "Postre", "Manzana"],
    },
    {
        "titulo": "Fondue de Queso Suiza",
        "descripcion": "El clásico suizo para compartir: quesos Gruyère y Emmental fundidos con vino blanco y kirsch.",
        "tipo_cocina": "Suiza",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 20},
        "ingredientes": [
            {"nombre": "Gruyère rallado", "cantidad": "300", "unidad": "g"},
            {"nombre": "Emmental rallado", "cantidad": "300", "unidad": "g"},
            {"nombre": "Vino blanco seco", "cantidad": "250", "unidad": "ml"},
            {"nombre": "Kirsch (aguardiente de cereza)", "cantidad": "2", "unidad": "cucharadas"},
            {"nombre": "Maicena", "cantidad": "1", "unidad": "cucharada"},
            {"nombre": "Ajo", "cantidad": "1", "unidad": "diente"},
            {"nombre": "Pan rústico para mojar", "cantidad": "400", "unidad": "g"},
        ],
        "pasos": [
            "Frotar el caquelon (olla de fondue) con el ajo partido.",
            "Calentar el vino blanco sin que hierva.",
            "Añadir los quesos rallados poco a poco removiendo con varilla en forma de ocho.",
            "Disolver la maicena en el kirsch y añadir. Remover hasta obtener una crema homogénea.",
            "Mantener caliente en el infiernillo. Servir con dados de pan para mojar.",
        ],
        "etiquetas": ["Suiza", "Queso", "Compartir", "Sin gluten"],
    },
    # ─── REINO UNIDO E IRLANDA ────────────────────────────────────────────
    {
        "titulo": "Shepherd's Pie",
        "descripcion": "El pastel inglés de cordero picado con salsa y puré de patata dorado al horno.",
        "tipo_cocina": "Británica",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 60},
        "ingredientes": [
            {"nombre": "Cordero picado", "cantidad": "600", "unidad": "g"},
            {"nombre": "Patatas para puré", "cantidad": "800", "unidad": "g"},
            {"nombre": "Zanahoria", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Caldo de cordero", "cantidad": "300", "unidad": "ml"},
            {"nombre": "Salsa Worcestershire", "cantidad": "1", "unidad": "cucharada"},
            {"nombre": "Mantequilla", "cantidad": "50", "unidad": "g"},
            {"nombre": "Leche", "cantidad": "100", "unidad": "ml"},
        ],
        "pasos": [
            "Sofreír la cebolla y la zanahoria. Añadir el cordero y dorar bien.",
            "Añadir el caldo y la salsa Worcestershire. Cocer 15 minutos.",
            "Cocer las patatas, hacer un puré con mantequilla y leche.",
            "Pasar la carne a una fuente. Cubrir con el puré y marcar con tenedor.",
            "Hornear a 200 °C 25 minutos hasta que el puré esté dorado.",
        ],
        "etiquetas": ["Reino Unido", "Cordero", "Horno"],
    },
    {
        "titulo": "Beef Wellington",
        "descripcion": "El lomo de ternera en costra de hojaldre con duxelles de champiñones, la pieza de resistencia británica.",
        "tipo_cocina": "Británica",
        "dificultad": "Difícil",
        "porciones": 4,
        "tiempos": {"total_minutos": 90},
        "ingredientes": [
            {"nombre": "Solomillo de ternera", "cantidad": "700", "unidad": "g"},
            {"nombre": "Hojaldre", "cantidad": "400", "unidad": "g"},
            {"nombre": "Champiñones", "cantidad": "400", "unidad": "g"},
            {"nombre": "Jamón serrano en lonchas", "cantidad": "8", "unidad": "lonchas"},
            {"nombre": "Mostaza de Dijon", "cantidad": "2", "unidad": "cucharadas"},
            {"nombre": "Yema de huevo", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Ajo", "cantidad": "2", "unidad": "dientes"},
        ],
        "pasos": [
            "Sellar el solomillo salpimentado por todos lados. Enfriar y pintar con mostaza.",
            "Triturar champiñones con ajo y secar en sartén hasta obtener una pasta (duxelles).",
            "Extender el jamón en film, cubrir con duxelles y enrollar el solomillo. Refrigerar 30 min.",
            "Envolver en hojaldre, sellar bien y pintar con yema.",
            "Hornear a 200 °C 25-30 minutos para punto medio. Reposar 10 min antes de cortar.",
        ],
        "etiquetas": ["Reino Unido", "Ternera", "Hojaldre", "Especial"],
    },
    # ─── GRECIA Y MEDITERRÁNEO ORIENTAL ──────────────────────────────────
    {
        "titulo": "Spanakopita (Empanada de Espinacas)",
        "descripcion": "El hojaldre griego crujiente con relleno de espinacas y queso feta, irresistible caliente o frío.",
        "tipo_cocina": "Griega",
        "dificultad": "Media",
        "porciones": 6,
        "tiempos": {"total_minutos": 60},
        "ingredientes": [
            {"nombre": "Masa filo", "cantidad": "250", "unidad": "g"},
            {"nombre": "Espinacas frescas", "cantidad": "500", "unidad": "g"},
            {"nombre": "Queso feta", "cantidad": "250", "unidad": "g"},
            {"nombre": "Huevos", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Cebolla tierna", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Eneldo fresco", "cantidad": "1", "unidad": "manojo"},
            {"nombre": "Aceite de oliva o mantequilla", "cantidad": "80", "unidad": "ml"},
        ],
        "pasos": [
            "Blanquear las espinacas, escurrir y picar.",
            "Mezclar con el feta desmenuzado, los huevos, la cebolla tierna y el eneldo.",
            "Pintar cada hoja de filo con aceite o mantequilla.",
            "Alternar capas de filo, añadir el relleno y cubrir con más capas de filo pintadas.",
            "Marcar en porciones y hornear a 180 °C 35-40 minutos hasta dorar.",
        ],
        "etiquetas": ["Grecia", "Vegetariana", "Filo", "Queso"],
    },
    {
        "titulo": "Kleftiko de Cordero",
        "descripcion": "Cordero cocinado lentamente en papillote con hierbas mediterráneas hasta que la carne cae sola del hueso.",
        "tipo_cocina": "Griega",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 240},
        "ingredientes": [
            {"nombre": "Pierna de cordero troceada", "cantidad": "1.5", "unidad": "kg"},
            {"nombre": "Ajo", "cantidad": "6", "unidad": "dientes"},
            {"nombre": "Limón", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Orégano seco", "cantidad": "2", "unidad": "cucharaditas"},
            {"nombre": "Tomillo", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Tomates maduros", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Aceite de oliva", "cantidad": "4", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Marinar el cordero con ajo, limón, hierbas, aceite, sal y pimienta 2 horas.",
            "Colocar cada trozo sobre papel de aluminio con los tomates en rodajas.",
            "Cerrar herméticamente los paquetes (papillote).",
            "Hornear a 160 °C durante 3 horas. Abrir los paquetes los últimos 20 min para dorar.",
        ],
        "etiquetas": ["Grecia", "Cordero", "Sin gluten"],
    },
    # ─── EUROPA DEL ESTE ─────────────────────────────────────────────────
    {
        "titulo": "Beef Stroganoff",
        "descripcion": "Tiras de ternera en salsa cremosa de crema agria y champiñones, el clásico ruso servido con noodles.",
        "tipo_cocina": "Rusa",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 35},
        "ingredientes": [
            {"nombre": "Solomillo de ternera en tiras", "cantidad": "600", "unidad": "g"},
            {"nombre": "Champiñones", "cantidad": "300", "unidad": "g"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Nata agria o crème fraîche", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Caldo de ternera", "cantidad": "150", "unidad": "ml"},
            {"nombre": "Mostaza", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Mantequilla", "cantidad": "40", "unidad": "g"},
            {"nombre": "Noodles o arroz para servir", "cantidad": "300", "unidad": "g"},
        ],
        "pasos": [
            "Saltear las tiras de ternera a fuego muy fuerte 2 minutos. Reservar.",
            "En la misma sartén, pochar la cebolla y los champiñones.",
            "Añadir el caldo y la mostaza. Reducir.",
            "Incorporar la nata agria y dejar espesar 5 minutos.",
            "Añadir la ternera y calentar sin hervir. Servir sobre noodles o arroz.",
        ],
        "etiquetas": ["Rusia", "Ternera", "Cremoso"],
    },
    {
        "titulo": "Borscht (Sopa de Remolacha)",
        "descripcion": "La sopa de remolacha ucraniana de color rubí intenso, con col, zanahoria y crème fraîche.",
        "tipo_cocina": "Ucraniana",
        "dificultad": "Fácil",
        "porciones": 6,
        "tiempos": {"total_minutos": 60},
        "ingredientes": [
            {"nombre": "Remolacha", "cantidad": "4", "unidad": "piezas"},
            {"nombre": "Col blanca", "cantidad": "300", "unidad": "g"},
            {"nombre": "Zanahoria", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Patatas", "cantidad": "3", "unidad": "piezas"},
            {"nombre": "Cebolla", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Tomate triturado", "cantidad": "200", "unidad": "g"},
            {"nombre": "Caldo de ternera o verduras", "cantidad": "1.5", "unidad": "litros"},
            {"nombre": "Crème fraîche para servir", "cantidad": "100", "unidad": "g"},
            {"nombre": "Eneldo fresco", "cantidad": "1", "unidad": "manojo"},
        ],
        "pasos": [
            "Sofreír cebolla y zanahoria. Añadir la remolacha rallada y el tomate.",
            "Verter el caldo y llevar a ebullición.",
            "Añadir la col en juliana y las patatas en cubos. Cocer 20 minutos.",
            "Rectificar de sal y vinagre (la sopa debe ser ligeramente ácida).",
            "Servir con crème fraîche y eneldo picado.",
        ],
        "etiquetas": ["Ucrania", "Sopa", "Vegano sin crème fraîche"],
    },
    {
        "titulo": "Köttbullar (Albóndigas Suecas)",
        "descripcion": "Las famosas albóndigas suecas en salsa cremosa, acompañadas de mermelada de arándanos rojos.",
        "tipo_cocina": "Escandinava",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 40},
        "ingredientes": [
            {"nombre": "Carne picada mixta cerdo+ternera", "cantidad": "500", "unidad": "g"},
            {"nombre": "Cebolla rallada", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Pan rallado", "cantidad": "50", "unidad": "g"},
            {"nombre": "Huevo", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Leche", "cantidad": "50", "unidad": "ml"},
            {"nombre": "Nata líquida", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Caldo de ternera", "cantidad": "300", "unidad": "ml"},
            {"nombre": "Mermelada de arándanos", "cantidad": "4", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Remojar el pan rallado en la leche. Mezclar con la carne, huevo, cebolla y especias.",
            "Formar albóndigas del tamaño de una nuez. Freír en mantequilla hasta dorar.",
            "En la misma sartén, añadir el caldo y la nata. Reducir para hacer la salsa.",
            "Incorporar las albóndigas y cocer 10 minutos.",
            "Servir con puré de patata y mermelada de arándanos.",
        ],
        "etiquetas": ["Suecia", "Cerdo", "Ternera", "Nórdico"],
    },
    {
        "titulo": "Moules-Frites Belgas",
        "descripcion": "Mejillones al vapor con vino blanco, chalota y perejil, acompañados de patatas fritas crujientes.",
        "tipo_cocina": "Belga",
        "dificultad": "Fácil",
        "porciones": 2,
        "tiempos": {"total_minutos": 25},
        "ingredientes": [
            {"nombre": "Mejillones frescos", "cantidad": "1.5", "unidad": "kg"},
            {"nombre": "Chalota", "cantidad": "3", "unidad": "piezas"},
            {"nombre": "Ajo", "cantidad": "2", "unidad": "dientes"},
            {"nombre": "Vino blanco seco", "cantidad": "200", "unidad": "ml"},
            {"nombre": "Mantequilla", "cantidad": "40", "unidad": "g"},
            {"nombre": "Perejil fresco", "cantidad": "1", "unidad": "manojo"},
            {"nombre": "Patatas para freír", "cantidad": "600", "unidad": "g"},
        ],
        "pasos": [
            "Limpiar y desbarbar los mejillones. Desechar los abiertos.",
            "Sofreír chalota y ajo en mantequilla. Añadir el vino y llevar a ebullición.",
            "Incorporar los mejillones, tapar y cocer 4-5 minutos hasta que se abran.",
            "Añadir perejil picado. Desechar los que no se hayan abierto.",
            "Servir en la olla con las patatas fritas y mayonesa.",
        ],
        "etiquetas": ["Bélgica", "Mariscos", "Fritos", "Sin gluten"],
    },
    # ─── MEDITERRÁNEO: MÁS PLATOS ─────────────────────────────────────────
    {
        "titulo": "Espinacas con Garbanzos (Sevilla)",
        "descripcion": "El guiso sevillano de espinacas y garbanzos en salsa de comino y especias, típico de Semana Santa.",
        "tipo_cocina": "Española",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 30},
        "ingredientes": [
            {"nombre": "Garbanzos cocidos", "cantidad": "400", "unidad": "g"},
            {"nombre": "Espinacas frescas", "cantidad": "500", "unidad": "g"},
            {"nombre": "Ajo", "cantidad": "4", "unidad": "dientes"},
            {"nombre": "Pan frito", "cantidad": "2", "unidad": "rebanadas"},
            {"nombre": "Comino", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Pimentón", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Vinagre de Jerez", "cantidad": "1", "unidad": "cucharada"},
            {"nombre": "Aceite de oliva", "cantidad": "4", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Saltear las espinacas hasta que se reduzcan. Reservar.",
            "Freír el pan y el ajo hasta dorar. Triturar con el comino y el pimentón.",
            "Sofreír el majado en aceite. Añadir los garbanzos y las espinacas.",
            "Añadir el vinagre y caldo si hace falta. Cocer 10 minutos.",
        ],
        "etiquetas": ["Andalucía", "España", "Vegano", "Legumbres", "Vigilia"],
    },
    {
        "titulo": "Croque Monsieur",
        "descripcion": "El sándwich tostado francés con jamón y queso Gruyère gratinado con bechamel, símbolo del café parisino.",
        "tipo_cocina": "Francesa",
        "dificultad": "Fácil",
        "porciones": 2,
        "tiempos": {"total_minutos": 20},
        "ingredientes": [
            {"nombre": "Pan de molde grueso", "cantidad": "4", "unidad": "rebanadas"},
            {"nombre": "Jamón cocido", "cantidad": "100", "unidad": "g"},
            {"nombre": "Gruyère rallado", "cantidad": "100", "unidad": "g"},
            {"nombre": "Mantequilla", "cantidad": "20", "unidad": "g"},
            {"nombre": "Leche", "cantidad": "150", "unidad": "ml"},
            {"nombre": "Harina", "cantidad": "15", "unidad": "g"},
            {"nombre": "Nuez moscada", "cantidad": "1", "unidad": "pizca"},
        ],
        "pasos": [
            "Hacer una bechamel espesa con mantequilla, harina, leche y nuez moscada.",
            "Montar los sándwiches con jamón y queso entre las rebanadas.",
            "Untar bechamel por encima y espolvorear más Gruyère.",
            "Gratinar en el horno a 200 °C 8-10 minutos hasta que burbujee y esté dorado.",
        ],
        "etiquetas": ["Francia", "Sándwich", "Rápido", "Gratinado"],
    },
    {
        "titulo": "Hummus de Remolacha",
        "descripcion": "Versión vibrante del hummus con remolacha asada, tahini y comino, colorida y nutritiva.",
        "tipo_cocina": "Mediterránea",
        "dificultad": "Fácil",
        "porciones": 4,
        "tiempos": {"total_minutos": 60},
        "ingredientes": [
            {"nombre": "Garbanzos cocidos", "cantidad": "400", "unidad": "g"},
            {"nombre": "Remolacha cocida", "cantidad": "200", "unidad": "g"},
            {"nombre": "Tahini", "cantidad": "3", "unidad": "cucharadas"},
            {"nombre": "Limón", "cantidad": "1", "unidad": "pieza"},
            {"nombre": "Ajo", "cantidad": "1", "unidad": "diente"},
            {"nombre": "Comino", "cantidad": "1", "unidad": "cucharadita"},
            {"nombre": "Aceite de oliva", "cantidad": "4", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Triturar todos los ingredientes en una batidora potente.",
            "Añadir agua fría poco a poco para ajustar la textura.",
            "Rectificar de sal, limón y comino al gusto.",
            "Servir con aceite de oliva y semillas de sésamo. Acompañar con pan pita.",
        ],
        "etiquetas": ["Mediterráneo", "Vegano", "Sin gluten", "Aperitivo"],
    },
    {
        "titulo": "Gazpacho Manchego (Gachas)",
        "descripcion": "No confundir con el andaluz: guiso manchego de caza o pollo con torta de pastor.",
        "tipo_cocina": "Española",
        "dificultad": "Media",
        "porciones": 4,
        "tiempos": {"total_minutos": 50},
        "ingredientes": [
            {"nombre": "Pollo o conejo troceado", "cantidad": "600", "unidad": "g"},
            {"nombre": "Torta de pastor (pan ácimo)", "cantidad": "200", "unidad": "g"},
            {"nombre": "Ajo", "cantidad": "4", "unidad": "dientes"},
            {"nombre": "Pimiento rojo seco", "cantidad": "2", "unidad": "piezas"},
            {"nombre": "Setas o champiñones", "cantidad": "200", "unidad": "g"},
            {"nombre": "Tomillo y romero", "cantidad": "al gusto", "unidad": ""},
            {"nombre": "Aceite de oliva", "cantidad": "4", "unidad": "cucharadas"},
        ],
        "pasos": [
            "Sofreír el ajo y los pimientos en aceite. Añadir la carne y dorar bien.",
            "Incorporar las setas y las hierbas. Cubrir con agua y cocer 20 minutos.",
            "Trocear la torta y añadirla al guiso.",
            "Cocer otros 10 minutos removiendo hasta que la torta absorba el caldo y quede cremoso.",
        ],
        "etiquetas": ["Castilla-La Mancha", "Caza", "España"],
    },
]


async def seed():
    async with httpx.AsyncClient(timeout=60.0) as client:
        # Obtener títulos existentes
        r = await client.get(f"{API}/api/recipes", params={"limit": 500})
        existing = {rec["titulo"].lower() for rec in r.json().get("recipes", [])}

        added, skipped = 0, 0
        for recipe in RECIPES:
            if recipe["titulo"].lower() in existing:
                print(f"  ↷ Ya existe: {recipe['titulo']}")
                skipped += 1
                continue
            r = await client.post(f"{API}/api/recipes/save", json={"recipe": recipe})
            if r.status_code == 200:
                print(f"  ✓ Añadida:  {recipe['titulo']}")
                added += 1
            else:
                print(f"  ✗ Error {r.status_code}: {recipe['titulo']}")

        print(f"\n{'─'*50}")
        print(f"  Añadidas: {added}  |  Ya existían: {skipped}")
        r = await client.get(f"{API}/api/stats")
        print(f"  Total en BD: {r.json()['total_recipes']} recetas")


if __name__ == "__main__":
    asyncio.run(seed())
